# rails requires a dummy DB config even fi you aren't using one
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: stubbed-redirect-db

development:
  <<: *default

production:
  <<: *default
